package dev.axeldiego.realchatapi.service.impl;

import dev.axeldiego.realchatapi.dto.UserDto;
import dev.axeldiego.realchatapi.entity.User;
import dev.axeldiego.realchatapi.exception.ResourceNotFoundException;
import dev.axeldiego.realchatapi.mapper.UserMapper;
import dev.axeldiego.realchatapi.repository.UserRepository;
import dev.axeldiego.realchatapi.service.UserService;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;

import java.util.List;
import java.util.stream.Collectors;

@Service
@RequiredArgsConstructor
public class UserServiceImpl implements UserService {

    private final UserRepository userRepository;

    @Override
    public UserDto createUser(UserDto userDto) {
        User user = UserMapper.toEntity(userDto);
        user.setId(null); // ensure id generated by Mongo
        User saved = userRepository.save(user);
        return UserMapper.toDto(saved);
    }

    @Override
    public UserDto getUserById(String id) {
        User user = userRepository.findById(id)
                .orElseThrow(() -> new ResourceNotFoundException("User not found with id: " + id));
        return UserMapper.toDto(user);
    }

    @Override
    public List<UserDto> getAllUsers() {
        return userRepository.findAll().stream()
                .map(UserMapper::toDto)
                .collect(Collectors.toList());
    }

    @Override
    public UserDto updateUser(String id, UserDto userDto) {
        User existing = userRepository.findById(id)
                .orElseThrow(() -> new ResourceNotFoundException("User not found with id: " + id));
        existing.setUsername(userDto.getUsername());
        existing.setEmail(userDto.getEmail());
        User saved = userRepository.save(existing);
        return UserMapper.toDto(saved);
    }

    @Override
    public void deleteUser(String id) {
        if (!userRepository.existsById(id)) {
            throw new ResourceNotFoundException("User not found with id: " + id);
        }
        userRepository.deleteById(id);
    }
}

